name: Bump branches

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  bump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ['staging']
    steps:
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push branch
        env:
          BRANCH: ${{ matrix.branch }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        run: |
          git switch -c ${BRANCH}-v${VERSION} v${VERSION}
          git push -u origin ${BRANCH}-v${VERSION}

      - name: Create pull request
        uses: actions/github-script@v6
        env:
          BRANCH: ${{ matrix.branch }}
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          # github-token: ${{secrets.GITHUB_TOKEN}}
          github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          script: |
            github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `chore(*): bump ${process.env.BRANCH} v${process.env.VERSION}`,
              body: `Bump ${process.env.BRANCH} [v${process.env.VERSION}](https://github.com/${context.repo.owner}/${context.repo.repo}/releases/tag/v${process.env.VERSION})`,
              head: `${context.repo.owner}:${process.env.BRANCH}-v${process.env.VERSION}`,
              base: process.env.BRANCH
            })
