name: Bump version

on: [workflow_dispatch]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Switch branch
        run: git switch -c tmp
      - name: Bump version
        run: npm run release
      - name: Get version
        id: get_version
        run: |
          PACKAGE_VERSION=cat package.json | grep version | cut -d " " -f 4 | tr -d "," | tr -d '"'
          echo ::set-output name=VERSION::v${PACKAGE_VERSION}
      - name: Push branch
        run: |
          git branch -m bump-${VERSION}
          git push -u origin bump-${VERSION}
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
      - name: Create pull request
        uses: actions/github-script@v2
        env:
          VERSION: ${{ steps.get_version.outputs.VERSION }}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          #github-token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
        script: |
          github.pulls.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'chore(*): bump ' + process.env.VERSION,
            head: context.repo.owner + ':' + 'bump-' + process.env.VERSION,
            base: master
          })