name: Release

on:
  pull_request:
    branches:
      - master
    types: [closed]
  
jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'bump-v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: echo ::set-output name=VERSION::${HEAD_REF#bump-v}
      env:
        HEAD_REF: ${{ github.event.pull_request.head.ref }}
    - name: Extract changelog
      id: extract_changelog
      run: echo ::set-output name=CHANGELOG::$(bash extract-release-note.sh)
      env:
        VERSION: ${{ github.get_version.outputs.VERSION }}
    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}
      with:
        tag_name: v${{ steps.get_version.outputs.VERSION }}
        release_name: v${{ steps.get_version.outputs.VERSION }}
        body: ${{ steps.extract_changelog.outputs.CHANGELOG }}
        draft: false
        prerelease: false