name: Release

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: github-release
          pull-request-title-pattern: "chore(*): bump${component} v${version}"
          release-type: node
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}